const mongoose = require('mongoose');

const studentSchema = new mongoose.Schema(
  {
    studentId: {
      type: String,
      required: false, // Will be auto-generated by pre-save hook
      unique: true,
      trim: true,
    },
    firstName: {
      type: String,
      required: [true, 'Please add a first name'],
      trim: true,
    },
    lastName: {
      type: String,
      required: [true, 'Please add a last name'],
      trim: true,
    },
    email: {
      type: String,
      required: [true, 'Please add an email'],
      unique: true,
      lowercase: true,
      match: [
        /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/,
        'Please add a valid email',
      ],
    },
    phone: {
      type: String,
      trim: true,
    },
    dateOfBirth: {
      type: Date,
    },
    gender: {
      type: String,
      enum: ['Male', 'Female', 'Other'],
    },
    address: {
      street: String,
      city: String,
      state: String,
      country: String,
      zipCode: String,
    },
    class: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Class',
      required: [true, 'Please assign a class'],
    },
    enrollmentDate: {
      type: Date,
      default: Date.now,
    },
    status: {
      type: String,
      enum: ['Active', 'Inactive', 'Graduated', 'Transferred'],
      default: 'Active',
    },
    boardingStatus: {
      type: String,
      enum: ['Day', 'Boarding'],
      default: 'Day',
    },
    guardian: {
      name: String,
      relationship: String,
      phone: String,
      email: String,
      address: String,
    },
    previousSchool: {
      name: String,
      address: String,
      lastGrade: String,
    },
    medicalInfo: {
      bloodGroup: String,
      allergies: [String],
      medicalConditions: [String],
      emergencyContact: String,
    },
    photo: {
      type: String,
      default: 'default-student.jpg',
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Virtual for full name
studentSchema.virtual('name').get(function () {
  return `${this.firstName} ${this.lastName}`;
});

// Generate unique student ID before saving
studentSchema.pre('save', async function (next) {
  if (this.isNew && !this.studentId) {
    let attempts = 0;
    let isUnique = false;
    let generatedId;
    
    // Retry up to 10 times to ensure uniqueness
    while (!isUnique && attempts < 10) {
      // Get the highest existing studentId number
      const lastStudent = await this.constructor
        .findOne({ studentId: { $exists: true } })
        .sort({ studentId: -1 })
        .select('studentId')
        .lean();
      
      let nextNumber = 1;
      if (lastStudent && lastStudent.studentId) {
        // Extract number from studentId (e.g., "STU001" -> 1)
        const match = lastStudent.studentId.match(/\d+$/);
        if (match) {
          nextNumber = parseInt(match[0], 10) + 1;
        }
      } else {
        // If no students exist, get count as fallback
        const count = await this.constructor.countDocuments();
        nextNumber = count + 1;
      }
      
      generatedId = `STU${String(nextNumber).padStart(3, '0')}`;
      
      // Check if this ID already exists
      const exists = await this.constructor.findOne({ studentId: generatedId });
      if (!exists) {
        isUnique = true;
      } else {
        // If exists, increment and try again
        nextNumber++;
        attempts++;
      }
    }
    
    // If still not unique after retries, add timestamp to make it unique
    if (!isUnique) {
      const timestamp = Date.now().toString().slice(-6);
      generatedId = `STU${timestamp}`;
    }
    
    this.studentId = generatedId;
  }
  next();
});

// Index for search
studentSchema.index({ firstName: 'text', lastName: 'text', email: 'text', studentId: 'text' });

module.exports = mongoose.model('Student', studentSchema);
