const mongoose = require('mongoose');

const studentSchema = new mongoose.Schema(
  {
    studentId: {
      type: String,
      required: false, // Will be auto-generated by pre-save hook
      unique: true,
      trim: true,
    },
    firstName: {
      type: String,
      required: [true, 'Please add a first name'],
      trim: true,
    },
    lastName: {
      type: String,
      required: [true, 'Please add a last name'],
      trim: true,
    },
    email: {
      type: String,
      required: [true, 'Please add an email'],
      unique: true,
      lowercase: true,
      match: [
        /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/,
        'Please add a valid email',
      ],
    },
    phone: {
      type: String,
      trim: true,
    },
    dateOfBirth: {
      type: Date,
    },
    gender: {
      type: String,
      enum: ['Male', 'Female', 'Other'],
    },
    address: {
      street: String,
      city: String,
      state: String,
      country: String,
      zipCode: String,
    },
    class: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Class',
      required: [true, 'Please assign a class'],
    },
    enrollmentDate: {
      type: Date,
      default: Date.now,
    },
    status: {
      type: String,
      enum: ['Active', 'Inactive', 'Graduated', 'Transferred'],
      default: 'Active',
    },
    boardingStatus: {
      type: String,
      enum: ['Day', 'Boarding'],
      default: 'Day',
    },
    guardian: {
      name: String,
      relationship: String,
      phone: String,
      email: String,
      address: String,
    },
    previousSchool: {
      name: String,
      address: String,
      lastGrade: String,
    },
    medicalInfo: {
      bloodGroup: String,
      allergies: [String],
      medicalConditions: [String],
      emergencyContact: String,
    },
    photo: {
      type: String,
      default: 'default-student.jpg',
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Virtual for full name
studentSchema.virtual('name').get(function () {
  return `${this.firstName} ${this.lastName}`;
});

// Generate student ID before validation and saving
studentSchema.pre('validate', async function (next) {
  if (this.isNew && !this.studentId) {
    const count = await this.constructor.countDocuments();
    this.studentId = `STU${String(count + 1).padStart(3, '0')}`;
  }
  next();
});

studentSchema.pre('save', async function (next) {
  if (this.isNew && !this.studentId) {
    const count = await this.constructor.countDocuments();
    this.studentId = `STU${String(count + 1).padStart(3, '0')}`;
  }
  next();
});

// Index for search
studentSchema.index({ firstName: 'text', lastName: 'text', email: 'text', studentId: 'text' });

module.exports = mongoose.model('Student', studentSchema);
