const mongoose = require('mongoose');

const teacherSchema = new mongoose.Schema(
  {
    teacherId: {
      type: String,
      required: false, // Will be auto-generated by pre-save hook
      unique: true,
      trim: true,
    },
    firstName: {
      type: String,
      required: [true, 'Please add a first name'],
      trim: true,
    },
    lastName: {
      type: String,
      required: [true, 'Please add a last name'],
      trim: true,
    },
    email: {
      type: String,
      required: [true, 'Please add an email'],
      unique: true,
      lowercase: true,
      match: [
        /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/,
        'Please add a valid email',
      ],
    },
    phone: {
      type: String,
      trim: true,
    },
    dateOfBirth: {
      type: Date,
    },
    gender: {
      type: String,
      enum: ['Male', 'Female', 'Other'],
    },
    address: {
      street: String,
      city: String,
      state: String,
      country: String,
      zipCode: String,
    },
    qualification: {
      type: String,
      trim: true,
    },
    specialization: {
      type: String,
      trim: true,
    },
    subjects: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Subject',
      },
    ],
    classes: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Class',
      },
    ],
    joiningDate: {
      type: Date,
      default: Date.now,
    },
    status: {
      type: String,
      enum: ['Active', 'Inactive', 'On Leave'],
      default: 'Active',
    },
    salary: {
      type: Number,
    },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    photo: {
      type: String,
      default: 'default-teacher.jpg',
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Virtual for full name
teacherSchema.virtual('name').get(function () {
  return `${this.firstName} ${this.lastName}`;
});

// Generate teacher ID before saving
teacherSchema.pre('save', async function (next) {
  if (this.isNew && !this.teacherId) {
    const count = await this.constructor.countDocuments();
    this.teacherId = `TCH${String(count + 1).padStart(3, '0')}`;
  }
  // Ensure teacherId is set before validation
  if (!this.teacherId) {
    const count = await this.constructor.countDocuments();
    this.teacherId = `TCH${String(count + 1).padStart(3, '0')}`;
  }
  next();
});

// Validate teacherId after it's been set
teacherSchema.pre('validate', async function (next) {
  if (this.isNew && !this.teacherId) {
    const count = await this.constructor.countDocuments();
    this.teacherId = `TCH${String(count + 1).padStart(3, '0')}`;
  }
  next();
});

// Index for search
teacherSchema.index({ firstName: 'text', lastName: 'text', email: 'text', teacherId: 'text' });

module.exports = mongoose.model('Teacher', teacherSchema);
